---

- name: Deploy filebeat
  unarchive:
    src: filebeat-{{ filebeat_version }}.tar.gz
    dest: "{{ filebeat_home_dir }}"
    creates: "{{ filebeat_home_dir }}/filebeat-{{ filebeat_version }}"
    copy: yes
    owner: tomcat
    group: tomcat
    # mode: ''

- name: copy startup script
  template:
    src: reload.sh.j2
    dest: "{{ filebeat_home_dir }}/reload.sh"
    owner: tomcat
    group: tomcat
    # mode: 0644
    
- name: copy config file
  template:
    src: filebeat.yml.j2
    dest: "{{ filebeat_home_dir }}/filebeat.yml"
    owner: tomcat
    group: tomcat
    # mode: 0644
  notify:
    - restart filebeat
  tags: reconfig